### ISSUE TITLE
Switching the demo to use Transvoxel

### ISSUE THREAD

**Issue by radishes** [Zylann/voxelgame#53]
I've been running the voxelgame demo project and messing around with it. This is awesome, thank you for publishing it!

Is it possible for me to modify the demo to use smooth Transvoxel rendering? I've been poking around and have not been able to figure out how to do this.

**Comment by Zylann** [comment]
It's not trivial to do this, the transvoxel meshing has no physics at the moment and has no texturing. Also, the data is different from a Minecraft-style demo:

Technically, you only need the VoxelProvider to fill the `Voxel.CHANNEL_ISOLEVEL` channel, where numbers above zero mean "absence of matter" and numbers below zero mean "presence of matter" (or maybe the opposite, I forgot). Currently only `CHANNEL_TYPE` is filled by the demo (where each voxel maps to a cube type).

**Comment by FreeLikeGNU** [comment]
I compiled your modules and ran this game nicely in Linux (Xubuntu 16.04) great work!  I too hope to see your progress on transvoxel!

**Comment by sjb8100** [comment]
is TransVoxel the new name for the OpenVoxel implemented in 3.1 mentioned here? "IMPORTANT: Godot 3.1 now integrates OpenSimplex under a very similar API, 
as a result this module is no longer maintained in Godot 3.1 onwards. " https://github.com/Zylann/godot_opensimplex/commit/f8b93c4fb6766413d7c5f0fc4170388e532055e1

How do you recommend we use this /voxelgame/ repo moving forward? do you plan to update it to the built in voxel solution?

**Comment by Zylann** [comment]
What was added to Godot 3.1 has nothing to do with voxels or Transvoxel, it only provides an official way to generate simplex noise. Transvoxel is a totally different thing.

This demo used a custom OpenSimplex module in addition to my voxel module in the past because it was not in the engine, and to simplify things I actually took out the OpenSimplex part, and used a simple heightmap image, because the goal of this demo is to show a simple example of my voxel module. It does not focus on terrain generation in particular.

Now that OpenSimplex is included in 3.1, I could eventually switch the heightmap back to OpenSimplex to make it a bit more interesting, but it's not really a priority for the time I have at the moment.

**Comment by sjb8100** [comment]
good info. I was looking at doing a area effect graphic that would switch the ground from cube voxels to TransVoxels (looking like smooth terrain) of course the end game is principled bsdf on both. take megascans for the cube voxels and some type of texture array / splat map solution for terrain and bonus if can be saved out at runtime to a heightmap. that I assume is many folks end goal. with that stated...

I did notice that your terrain solution is presently the standard for godot, talks have started about solving it in engine but I am not sure where those talks have stopped.

my biggest priority is to have a smooth terrain that you can dig caves in at runtime and looks nice. bonus if the framework can be ported out the cube voxels and tie in with an open source Minecraft backend like TrueCraft available on GitHub.

I am new to c++ and godot but I am willing to help this repo and others in this regard. I assume an irc channel or typical discord type chat is the best way to connect with the core community of godot?

**Comment by Zylann** [comment]
The demo now uses transvoxel in `res://smooth_terrain/main.tscn`.
