### ISSUE TITLE
Caves/tunnels support

### ISSUE THREAD

**Issue by NewNodeGames** [Zylann/voxelgame#56]
This is not an issue, only a idea or suggestion. I know that with left click I can destroy voxels, but can be nice maps with random caves or tunnels directly created for explore. Is hard or easy to implement?

**Comment by Zylann** [comment]
I have ideas how to implement structure generation (aka anything bigger than 1 voxel with some procedural rules) but I am not sure it will end up here, because caves are not a generic feature (as well as anything not purely related to rendering voxels).

Also, see this: https://github.com/Zylann/godot_voxel/issues/17

**Comment by NewNodeGames** [comment]
Seems to be implemented on tinmanjuggernaut fork. Closing.
